name: Release

on:
  push:
    branches:
      - main
    # paths:
      # - 'perforator/ui/packages/**'


jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.3
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      working-directory: perforator/ui/app
      run: pnpm install
    - name: "Set token"
      run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      env:
          NPM_TOKEN: ${{ secrets.NPMJS_TOKEN }}
    - name: Build
      working-directory: perforator/ui/app
      run: |
          pnpm --filter '../packages/*' run build
    - name: Bump version
      working-directory: perforator/ui/app
      run: |
          pnpm --filter '../packages/*' run bump
    - name: Publish
      working-directory: perforator/ui/app
      run: |
          pnpm --filter '../packages/*' run delete-engines
          pnpm --filter '../packages/*' publish --no-git-checks --tag test-ci --access public
